# Generated by Django 4.2.2 on 2023-06-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
