# Generated by Django 4.2.2 on 2023-06-08 22:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_time_sold',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date_sold', models.DateTimeField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.products')),
            ],
        ),
    ]
