# Generated by Django 4.2.2 on 2023-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_sells_product_name_adds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='cost',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
