# Generated by Django 4.2.1 on 2023-06-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_alter_adds_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='product_name',
            field=models.CharField(default=None, max_length=225),
        ),
    ]
